### ISSUE TITLE
make download_tools command is missing in the main README.md

### ISSUE THREAD

**Issue by lpiwowar** [openstack-k8s-operators/install_yamls#697]
It would be nice if we had the `make download_tools` command in the main README.md. I was following the guide and got stuck for a moment due to missing commands like kubectl or htpasswd.

**Comment by jpodivin** [comment]
The issue was resolved by https://github.com/openstack-k8s-operators/install_yamls/commit/534095dbfb64968223ef21e6c79a809fd6c93cab from @fao89.
